services:
  db:
    image: andress002/mi-postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    image: andress002/nestjs-backend:latest
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  frontend:
    image: andress002/angular-frontend:latest
    ports:
      - '4200:80'
    depends_on:
      - backend
